/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.chase22;

import io.github.chase22.config.TelegramBotApiConfiguration;
import io.github.chase22.infrastructure.server.ApiServer;
import io.github.chase22.infrastructure.server.DependencyRegistry;

import java.util.Objects;

public class TelegramBotApiMock {
    private ApiServer apiServer;
    public static TelegramBotApiConfiguration configuration;

    public TelegramBotApiMock(final TelegramBotApiConfiguration configuration) {
        TelegramBotApiMock.configuration = configuration;
    }

    public void start(int port) {
        try {
            final DependencyRegistry registry = new DependencyRegistry(port, configuration);
            apiServer = registry.apiServer;
            apiServer.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void stop() throws Exception {
        if (Objects.nonNull(apiServer)) {
            apiServer.stop();
        }
    }
}
