/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package io.github.Chase22.telegram.telegrambotapimock

import spock.lang.Specification

class TelegramBotApiMockTest extends Specification {

}
