/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package io.github.Chase22.telegram.telegrambotapimock


import spock.lang.Specification
import spock.lang.Subject

class TelegramBotApiMockSpec extends Specification {

    @Subject
    TelegramBotApiMock apiMock = new TelegramBotApiMock()

    def "Should start a server on the given port"() {
        def port = 50300
        when:
        apiMock.start(port)

        then:
        HttpURLConnection conn = new URL("http://localhost:50300/health").openConnection() as HttpURLConnection
        conn.getResponseCode() == 404

    }
}
