/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.chase22

import io.github.chase22.config.TelegramBotApiConfiguration
import io.github.chase22.infrastructure.server.DependencyRegistry

class TelegramBotApiMock(configuration: TelegramBotApiConfiguration, port: Int) {
    private val registry = DependencyRegistry(port, configuration)

    fun start() {
        try {
            registry.apiServer.start()
        } catch (e: Exception) {
            e.printStackTrace()
        }

    }

    fun stop() = registry.apiServer.stop()
}
